[[headers]]
  for = "/*" # Apply this rule to all paths
  [headers.values]
    # Define a Permissions-Policy.
    # We're listing common features and explicitly disabling them (or setting to self/none).
    # Crucially, we are omitting 'browsing-topics' or setting it to '()'
    # to prevent the "Unrecognized feature" warning.
    Permissions-Policy = "browsing-topics=(), accelerometer=(), autoplay=(), camera=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=()"

# This rule ensures that all paths are served by index.html,
# allowing client-side routing (React Router) to handle them.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200